# Nombre de la aplicacion
spring.application.name=libros

# Conexion PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/libros_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto de la aplicacion
server.port=${PORT:8080}